routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'PageController@index')->name('front.home');
Route::get ( '/redirect/{service}', 'SocialAuthController@redirect' );
Route::get ( '/callback/{service}', 'SocialAuthController@callback' );

Route::group([ 'middleware'=>['auth'] ],function(){
    Route::resource('category', 'CategoryController');
    Route::post('unique-category', 'CategoryController@validateDuplicateName')->name('unique-category');
    Route::resource('items', 'ItemController');
    Route::post('unique-item', 'CategoryController@validateDuplicateName')->name('unique-item');
    Route::get('/home', 'HomeController@index')->name('home');
});

app/Models/Items.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Items extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'item_name','item_description'
    ];

    public function categories(){
        return $this->belongsToMany( Categories::class , 'items_categories' , 'item_id' , 'category_id' );
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Items;
use App\Models\Categories;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $oItemList = Items::all();
        $oCategories = Categories::all();
        return view('admin.items.index',compact('oItemList','oCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!empty($request->id)){
            $objItem = Items::find($request->id);
            $objItem->update($request->all());
            $objItem->categories()->sync( $request->category_ids );
        }else{
            Items::create( $request->all() )->categories()->sync( $request->category_ids );
        }
        return redirect()->route('items.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $oItemDetail = Items::with(['categories'])->find($id);
        $oCategories = Categories::all();
        return view('admin.items.item_detail',compact('oItemDetail','oCategories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Items $item)
    {
        if(!empty($item->id)){
            $oItem = Items::with(['categories'])->find($item->id);
            $oItem->categories()->detach( $oItem->categories()->pluck('item_id') );
            $oItem->delete();
        }
    }
}

resources/views/admin/items/index.blade.php
@extends('layouts.admin.template')
@section('content')

<!-- Header End-->
<div class="row">
    <div class=" col-xs-12 col-sm-12">
        <div class="page_title view-page-title">
            <h2 class="mt-10">Items</h2>
        </div>
    </div>
</div>
<!-- page title row ends here-->

<!-- form -->
<div class="row">
    <div class="col-xs-12 col-sm-12">
        <div class="panel panel-default">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row custom-form-row-full">
                        <button data-target="#item_modal" class="add_item_btn action-link btn custom-btn custom-add-bordered-btn m-none" data-toggle="modal" href="javascript:;"><span class="glyphicon glyphicon-plus"></span> Add New Item</button>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<!-- table wrapper starts here -->
<div class="row table-contents-wrapper table-records-wrapper">
    <div class="col-xs-12 revenue-table-wrapper">
        <div class="table-responsive custom-record-table">
            <table class="table table-hover revenue-table myTable">
                <thead class="bg-color">
                    <tr>
                        <th>Item name</th>
                        <th>Description</th>
                        <th class="width-10">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($oItemList as $key => $oItem)
                    <tr>
                        <td>{{ $oItem->item_name }}</td>
                        <td>{{ $oItem->item_description }}</td>
                        <td>
                            <a href="javascript:;" data-target="#item_modal" class="action-link edit_item_btn" data-id="{{ $oItem->id }}" data-name="{{ $oItem->item_name }}" data-description="{{ $oItem->item_description }}" data-categories="{{ implode(',',$oItem->categories->pluck('id')->toArray()) }}"  data-toggle="modal">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                            <a href="javascript:;" class="action-link remove_item_btn"  data-item-id="{{ $oItem->id }}" data-url="{{ route('items.destroy',$oItem->id) }}">
                                <i class="glyphicon glyphicon-trash"></i> 
                            </a>
                            <a href="{{ route('items.show',$oItem->id) }}" class="action-link">
                                <i class="glyphicon glyphicon-eye-open"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>


@include('admin.modals.item_modal')
@endsection
@section('js')
  <script src="{{ asset('admin/js/custom-js/item.js') }}"></script>
@endsection

resources/views/admin/items/item_detail.blade.php
@extends('layouts.admin.template')
@section('content')

<!-- Header End-->
<div class="row">
    <div class=" col-xs-12 col-sm-12">
        <!-- <div class="inner_page_wrap"> -->
            <div class="page_title view-page-title">
                <h2 class="mt-10">Item Details</h2>
            </div>
        <!-- </div> -->
    </div>
</div>
<!-- page title row ends here-->

<div class="row">
    <div class="col-xs-12 col-sm-12">
        <div class="panel panel-default">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row custom-form-row-full">
                        <a href="javascript:;" data-target="#item_modal" class="edit_item_btn action-link btn custom-btn custom-add-bordered-btn m-none" data-id="{{ $oItemDetail->id }}" data-name="{{ $oItemDetail->item_name }}" data-description="{{ $oItemDetail->item_description }}" data-categories="{{ implode(',',$oItemDetail->categories->pluck('id')->toArray()) }}"  data-toggle="modal">
                            Edit
                        </a>
                        <a href="javascript:;" class="remove_item_btn action-link btn custom-btn custom-add-bordered-btn m-none"  data-item-id="{{ $oItemDetail->id }}" data-url="{{ route('items.destroy',$oItemDetail->id) }}">
                            Delete
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<!-- table wrapper starts here -->
<div class="row table-contents-wrapper table-records-wrapper">
    <div class="col-xs-12 revenue-table-wrapper">
        <div class="table-responsive custom-record-table">
            <table class="table table-hover revenue-table">
                <thead class="bg-color">
                    
                </thead>
                <tbody>
                    <tr>
                        <th>Item Name</th>
                        <td>{{ $oItemDetail->item_name }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ $oItemDetail->item_description }}</td>
                    </tr>
                    <tr>
                        <th>Categories</th>
                        <td>{{ implode( ' , ',$oItemDetail->categories->pluck('category_name')->toArray() ) }}</td>
                    </tr>
                    <tr>
                        <th>Created At</th>
                        <td>{{ date('d M , Y',strtotime($oItemDetail->created_at)) }}</td>
                    </tr>
                    <tr>
                        <th>Updated at</th>
                        <td>{{ date('d M , Y',strtotime($oItemDetail->updated_at)) }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- table wrapper ends here -->

@include('admin.modals.item_modal')
<!-- table wrapper ends here -->
@endsection
@section('js')
  <script src="{{ asset('admin/js/custom-js/item.js') }}"></script>
@endsection