routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'PageController@index')->name('front.home');
Route::get ( '/redirect/{service}', 'SocialAuthController@redirect' );
Route::get ( '/callback/{service}', 'SocialAuthController@callback' );

Route::group([ 'middleware'=>['auth'] ],function(){
    Route::resource('category', 'CategoryController');
    Route::post('unique-category', 'CategoryController@validateDuplicateName')->name('unique-category');
    Route::resource('items', 'ItemController');
    Route::post('unique-item', 'CategoryController@validateDuplicateName')->name('unique-item');
    Route::get('/home', 'HomeController@index')->name('home');
});

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Categories;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $oCategoriesList = Categories::with(['items'])->get();
        return view('admin.category.index',compact('oCategoriesList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!empty($request->id)){
            Categories::find($request->id)->update($request->all());
        }else{
            Categories::create( $request->all() );
        }
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $oCategoryDetail = Categories::find($id);
        return view('admin.category.category_detail',compact('oCategoryDetail'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categories $category)
    {
        Categories::find($category->id)->delete();
    }
    public function validateDuplicateName(Request $request){
        if(!empty($request->category_id)){
            $oCategory = Categories::where('category_name',$request->category_name)->where('id','<>',$request->category_id)->get();
        }else{
            $oCategory = Categories::where('category_name',$request->category_name)->get();
        }
        return response()->json($oCategory);
    }
}

resources/views/admin/category/category_detail.blade.php
@extends('layouts.admin.template')
@section('content')

<!-- Header End-->
<div class="row">
    <div class=" col-xs-12 col-sm-12">
        <!-- <div class="inner_page_wrap"> -->
            <div class="page_title view-page-title">
                <h2 class="mt-10">Category Details</h2>
            </div>
        <!-- </div> -->
    </div>
</div>
<!-- page title row ends here-->

<div class="row">
    <div class="col-xs-12 col-sm-12">
        <div class="panel panel-default">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row custom-form-row-full">
                        <a href="javascript:;" class="edit_category_btn action-link btn custom-btn custom-add-bordered-btn m-none" data-toggle="modal" data-target="#category_modal" data-id="{{ $oCategoryDetail->id }}" data-name="{{ $oCategoryDetail->category_name }}">
                            Edit
                        </a>
                        <a href="javascript:;" class="remove_category_btn action-link btn custom-btn custom-add-bordered-btn m-none" data-id="{{ $oCategoryDetail->id }}" data-url="{{ route('category.destroy',$oCategoryDetail->id) }}" data-item-counts="{{ count($oCategoryDetail->items) }}">
                            Delete
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<!-- table wrapper starts here -->
<div class="row table-contents-wrapper table-records-wrapper">
    <div class="col-xs-12 revenue-table-wrapper">
        <div class="table-responsive custom-record-table">
            <table class="table table-hover revenue-table">
                <thead class="bg-color">
                    
                </thead>
                <tbody>
                    <tr>
                        <th>Category Name</th>
                        <td>{{ $oCategoryDetail->category_name }}</td>
                    </tr>
                    <tr>
                        <th>Created At</th>
                        <td>{{ date('d M , Y',strtotime($oCategoryDetail->created_at)) }}</td>
                    </tr>
                    <tr>
                        <th>Updated at</th>
                        <td>{{ date('d M , Y',strtotime($oCategoryDetail->updated_at)) }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- table wrapper ends here -->

@include('admin.modals.category_modal')
<!-- table wrapper ends here -->
@endsection
@section('js')
  <script src="{{ asset('admin/js/custom-js/category.js') }}"></script>
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.admin.template')
@section('content')

<!-- Header End-->
<div class="row">
    <div class=" col-xs-12 col-sm-12">
        <!-- <div class="inner_page_wrap"> -->
        <div class="page_title view-page-title">
            <h2 class="mt-10">Categories</h2>
        </div>
        <!-- </div> -->
    </div>
</div>
<!-- page title row ends here-->

<!-- form -->
<div class="row">
    <div class="col-xs-12 col-sm-12">
        <div class="panel panel-default">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row custom-form-row-full">
                        <button data-target="#category_modal" class="add_category_btn action-link btn custom-btn custom-add-bordered-btn m-none" data-toggle="modal" href="javascript:;"><span class="glyphicon glyphicon-plus"></span> Add New Category</button>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- table wrapper starts here -->
<div class="row table-contents-wrapper table-records-wrapper">
    <div class="col-xs-12 revenue-table-wrapper">
        <div class="table-responsive custom-record-table">
            <table class="table table-hover revenue-table myTable">
                <thead class="bg-color">
                    <tr>
                        <th>Category name</th>
                        <th>No of Items</th>
                        <th class="width-10">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach( $oCategoriesList as $key => $oCategoryInfo )
                        <tr>
                            <td>{{ $oCategoryInfo->category_name }}</td>
                            <td>{{ count($oCategoryInfo->items) }}</td>
                            <td>
                                <a href="javascript:;" class="action-link edit_category_btn" data-toggle="modal" data-target="#category_modal" data-id="{{ $oCategoryInfo->id }}" data-name="{{ $oCategoryInfo->category_name }}">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </a>
                                <a href="javascript:;" class="action-link remove_category_btn" data-id="{{ $oCategoryInfo->id }}" data-url="{{ route('category.destroy',$oCategoryInfo->id) }}" data-item-counts="{{ count($oCategoryInfo->items) }}">
                                    <i class="glyphicon glyphicon-trash"></i> 
                                </a>
                                <a href="{{ route('category.show',$oCategoryInfo->id) }}" class="action-link">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                </a>
                            </td>
                        </tr>                      
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@include('admin.modals.category_modal')
<!-- table wrapper ends here -->
@endsection
@section('js')
  <script src="{{ asset('admin/js/custom-js/category.js') }}"></script>
@endsection